import type { Locale, LocalizedProject, Project, ProjectCopy } from "@/types/project";

const copy = (es: ProjectCopy, en: ProjectCopy) => ({ es, en });

const projectEntries: Project[] = [
  {
    slug: "mayma-bikinis", index: "01", name: "Mayma Bikinis", client: "Mayma Bikinis", year: "2026",
    url: "https://www.maymabikinis.com.ar/", featured: true,
    palette: { background: "#315757", foreground: "#fffdf9", accent: "#f0a298", muted: "#b8d9d5" },
    brandLogo: { src: "/work/mayma/brand-logo.png", alt: "Logo de Mayma Bikinis", width: 2042, height: 1274, contrast: "light" },
    cover: { src: "/work/mayma/cover.png", alt: "Bikini verde de Mayma Bikinis flotando sobre el agua", width: 1920, height: 840 },
    gallery: [
      { src: "/work/mayma/customizer.jpg", alt: "Bikini azul presentado en el personalizador Mayma Bikinis", width: 1080, height: 1350 },
      { src: "/work/mayma/product-04.jpg", alt: "Enteriza Mayma Bikinis en una escena de verano", width: 1080, height: 1350 },
      { src: "/work/mayma/detail.jpg", alt: "Detalle textil de un bikini Mayma Bikinis", width: 900, height: 1600 },
    ],
    copy: copy(
      {
        category: "Fashion / Swimwear / Ecommerce",
        description: "Un e-commerce mobile-first con catálogo, stock, personalización de bikinis y checkout integrado.",
        services: ["Diseño UX / UI", "Desarrollo ecommerce", "Personalizador", "Pagos e integraciones"],
        productCaseStudy: {
          heroImage: { src: "/work/mayma/screens/home.webp", alt: "Home de Mayma Bikinis con accesos al catálogo y al personalizador", width: 2940, height: 1604 },
          lead: "E-commerce mobile-first con personalización de bikinis, variantes, stock y un flujo de compra completo.",
          role: "Diseño de experiencia + desarrollo ecommerce",
          challengeTitle: "Vender online sin simplificar de más.",
          challenge: "Mayma necesitaba mostrar su catálogo y vender online, pero también conservar la posibilidad de elegir y combinar cada parte del bikini. La experiencia debía ordenar talles, medidas, telas, modelos y disponibilidad sin convertir la compra en un trámite.",
          sections: [
            {
              eyebrow: "01 / Personalizador",
              title: "Armá el bikini a tu manera.",
              text: "El recorrido empieza explicando con claridad qué se puede elegir y divide la personalización en siete pasos. La persona puede armar un conjunto completo o concentrarse en una sola pieza sin enfrentarse a todas las decisiones al mismo tiempo.",
              points: ["Conjunto completo o piezas individuales", "Progreso visible", "Resumen que se actualiza durante el recorrido"],
              images: [
                { src: "/work/mayma/screens/personalizador-intro.webp", alt: "Entrada al personalizador de Mayma con el recorrido de decisiones", width: 2940, height: 1606 },
                { src: "/work/mayma/screens/personalizador-prenda.webp", alt: "Primer paso del personalizador para elegir el tipo de prenda", width: 2938, height: 1600 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "02 / Decisiones guiadas",
              title: "Medidas, tela y modelo dentro del mismo flujo.",
              text: "Cada paso concentra una decisión concreta. Se puede elegir un talle o cargar medidas, recorrer telas reales, definir los modelos de corpiño y bombacha y ajustar el cavado. El resumen lateral mantiene visible lo elegido y reduce errores al avanzar.",
              points: ["Talles o medidas específicas", "Telas administrables con imágenes reales", "Modelos y cavado seleccionados visualmente"],
              images: [
                { src: "/work/mayma/screens/personalizador-medidas.webp", alt: "Paso para elegir talle o cargar medidas específicas", width: 2940, height: 1612 },
                { src: "/work/mayma/screens/personalizador-tela.webp", alt: "Selección de tela dentro del personalizador de bikinis", width: 2940, height: 1604 },
                { src: "/work/mayma/screens/personalizador-corpino.webp", alt: "Selección visual del modelo de corpiño", width: 2940, height: 1600 },
                { src: "/work/mayma/screens/personalizador-bombacha.webp", alt: "Selección visual del modelo de bombacha", width: 2940, height: 1600 },
                { src: "/work/mayma/screens/personalizador-cavado.webp", alt: "Último paso para elegir el nivel de cavado", width: 2940, height: 1600 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "03 / Consulta personalizada",
              title: "Un resumen listo para continuar por WhatsApp.",
              text: "El último paso reúne tipo de prenda, talle, medidas, tela, modelos y cavado. Mayma recibe la consulta con ese contexto para confirmar disponibilidad y valor sin pedirle a la persona que repita todo en una conversación.",
              points: ["Resumen completo antes de enviar", "Comentarios adicionales", "Consulta preparada para WhatsApp"],
              image: { src: "/work/mayma/screens/personalizador-resumen.webp", alt: "Resumen final del bikini personalizado antes de enviarlo por WhatsApp", width: 2936, height: 1612 },
              layout: "wide",
            },
            {
              eyebrow: "04 / Catálogo y producto",
              title: "Variantes claras, disponibilidad en contexto.",
              text: "El catálogo permite recorrer la colección y cada ficha reúne galería, precio, descuento por transferencia, talle, color y disponibilidad. La consulta de envío por código postal aparece dentro de la misma decisión de compra.",
              points: ["Catálogo visual", "Talles, colores y stock por variante", "Cálculo de envío con Correo Argentino"],
              images: [
                { src: "/work/mayma/screens/catalogo.webp", alt: "Catálogo de Mayma con productos, precios y descuento por transferencia", width: 2940, height: 1604 },
                { src: "/work/mayma/screens/producto.webp", alt: "Ficha de producto con talle, color, disponibilidad y acción de compra", width: 2940, height: 1604 },
                { src: "/work/mayma/screens/envio-producto.webp", alt: "Opciones de envío por código postal dentro de la ficha de producto", width: 2940, height: 1602 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "05 / Carrito y checkout",
              title: "Del producto al pago en pasos entendibles.",
              text: "El carrito conserva variante y cantidad antes de iniciar un checkout dividido en entrega, facturación y pago. La persona puede elegir retiro o Correo Argentino y pagar mediante transferencia o Mercado Pago.",
              points: ["Carrito con variante y cantidades", "Entrega antes de facturación", "Transferencia o Mercado Pago"],
              images: [
                { src: "/work/mayma/screens/carrito.webp", alt: "Carrito de Mayma con variante, cantidad y resumen del pedido", width: 2940, height: 1600 },
                { src: "/work/mayma/screens/checkout-entrega.webp", alt: "Primer paso del checkout para elegir retiro o envío por Correo Argentino", width: 2940, height: 1610 },
                { src: "/work/mayma/screens/checkout-pago-redacted.webp", alt: "Paso de pago anonimizado con transferencia bancaria y Mercado Pago", width: 1695, height: 928 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "06 / Administración",
              title: "La operación se gestiona desde el mismo producto.",
              text: "El panel permite revisar el estado general de la tienda, mantener productos y variantes y actualizar las telas disponibles en el personalizador. Los datos comerciales, inventario e identidades fueron ocultados en estas capturas.",
              points: ["Resumen operativo", "Productos, variantes y disponibilidad", "Telas personalizadas con imagen y estado"],
              images: [
                { src: "/work/mayma/screens/admin-resumen-redacted.webp", alt: "Panel administrativo de Mayma con métricas e identidades ocultas", width: 1696, height: 927 },
                { src: "/work/mayma/screens/admin-productos-redacted.webp", alt: "Gestión de productos con precios, stock e identificadores ocultos", width: 1696, height: 927 },
                { src: "/work/mayma/screens/admin-telas-redacted.webp", alt: "Gestión de telas disponibles para el personalizador, con email administrativo oculto", width: 1697, height: 927 },
              ],
              layout: "wide",
            },
          ],
          modulesLabel: "Qué construimos",
          modules: ["E-commerce y catálogo", "Personalizador de bikinis", "Talles, medidas y variantes", "Gestión de stock", "Carrito y checkout", "Mercado Pago y transferencia", "Correo Argentino y retiro", "Consulta personalizada por WhatsApp"],
          technologyLabel: "Tecnologías e integraciones",
          technologies: ["React", "Vite", "Neon PostgreSQL", "Mercado Pago", "Cloudinary", "Correo Argentino", "Vercel"],
          closing: "Una tienda donde la compra directa y la personalización conviven, cada una con el flujo que necesita.",
        },
        caseStudy: {
          statement: "El verano como interfaz: liviano, combinable y siempre en movimiento.",
          challenge: "Mayma Bikinis necesitaba vender productos con múltiples combinaciones de talle, color y modelo sin convertir la compra en un formulario frío.",
          approach: "Construimos una experiencia visual donde catálogo y personalización conviven. La jerarquía editorial mantiene el producto al frente y la interfaz acompaña con decisiones claras.",
          highlights: [
            { title: "Catálogo flexible", text: "Variantes, stock y colecciones se presentan sin perder ritmo visual." },
            { title: "Personalización", text: "Corpiños y bombachas pueden combinarse desde una experiencia guiada." },
            { title: "Identidad en movimiento", text: "Agua, coral y verde profundo traducen la energía de la marca." },
          ],
          outcome: "Una tienda cercana, expresiva y preparada para crecer con nuevas colecciones.",
        },
      },
      {
        category: "Fashion / Swimwear / Ecommerce",
        description: "A mobile-first ecommerce with a product catalogue, stock, custom swimwear and an integrated checkout.",
        services: ["UX / UI design", "Ecommerce development", "Product customiser", "Payments and integrations"],
        productCaseStudy: {
          heroImage: { src: "/work/mayma/screens/home.webp", alt: "Mayma Bikinis homepage with links to the catalogue and customiser", width: 2940, height: 1604 },
          lead: "A mobile-first ecommerce with bikini customisation, product variants, stock and a complete purchase flow.",
          role: "Experience design + ecommerce development",
          challengeTitle: "Sell online without oversimplifying the product.",
          challenge: "Mayma needed to present its catalogue and sell online while preserving the option to choose and match each part of a bikini. The experience had to organise sizes, measurements, fabrics, models and availability without turning the purchase into a chore.",
          sections: [
            {
              eyebrow: "01 / Customiser",
              title: "Build a bikini your way.",
              text: "The journey starts by explaining what can be chosen and divides customisation into seven steps. Customers can build a complete set or focus on one piece without facing every decision at once.",
              points: ["Complete sets or individual pieces", "Visible progress", "A summary that updates throughout the journey"],
              images: [
                { src: "/work/mayma/screens/personalizador-intro.webp", alt: "Mayma customiser entry page explaining each decision", width: 2940, height: 1606 },
                { src: "/work/mayma/screens/personalizador-prenda.webp", alt: "First customiser step for choosing the garment type", width: 2938, height: 1600 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "02 / Guided decisions",
              title: "Measurements, fabric and fit within one flow.",
              text: "Each step focuses on one decision. Customers can choose a standard size or enter measurements, browse real fabrics, define top and bottom styles and adjust the cut. The side summary keeps every choice visible and reduces mistakes.",
              points: ["Standard sizes or specific measurements", "Admin-managed fabrics with real images", "Visual selection for styles and cut"],
              images: [
                { src: "/work/mayma/screens/personalizador-medidas.webp", alt: "Step for choosing a size or entering specific measurements", width: 2940, height: 1612 },
                { src: "/work/mayma/screens/personalizador-tela.webp", alt: "Fabric selection within the bikini customiser", width: 2940, height: 1604 },
                { src: "/work/mayma/screens/personalizador-corpino.webp", alt: "Visual selection of a bikini top style", width: 2940, height: 1600 },
                { src: "/work/mayma/screens/personalizador-bombacha.webp", alt: "Visual selection of a bikini bottom style", width: 2940, height: 1600 },
                { src: "/work/mayma/screens/personalizador-cavado.webp", alt: "Final step for choosing the bottom cut", width: 2940, height: 1600 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "03 / Custom enquiry",
              title: "A complete summary ready for WhatsApp.",
              text: "The final step brings garment type, size, measurements, fabric, styles and cut together. Mayma receives the request with enough context to confirm availability and price without asking the customer to repeat every choice.",
              points: ["Complete review before sending", "Additional comments", "A request prepared for WhatsApp"],
              image: { src: "/work/mayma/screens/personalizador-resumen.webp", alt: "Final custom bikini summary before sending it through WhatsApp", width: 2936, height: 1612 },
              layout: "wide",
            },
            {
              eyebrow: "04 / Catalogue and product",
              title: "Clear variants, availability in context.",
              text: "The catalogue presents the collection while each product page brings gallery, price, bank-transfer discount, size, colour and availability together. Shipping estimates by postcode stay within the same purchase decision.",
              points: ["Visual catalogue", "Sizes, colours and stock by variant", "Correo Argentino shipping estimates"],
              images: [
                { src: "/work/mayma/screens/catalogo.webp", alt: "Mayma catalogue with products, prices and bank-transfer discounts", width: 2940, height: 1604 },
                { src: "/work/mayma/screens/producto.webp", alt: "Product page with size, colour, availability and purchase action", width: 2940, height: 1604 },
                { src: "/work/mayma/screens/envio-producto.webp", alt: "Postcode shipping options inside the product page", width: 2940, height: 1602 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "05 / Cart and checkout",
              title: "From product to payment in understandable steps.",
              text: "The cart keeps variant and quantity before starting a checkout divided into delivery, billing and payment. Customers can choose pickup or Correo Argentino and pay by bank transfer or Mercado Pago.",
              points: ["Cart with variants and quantities", "Delivery before billing", "Bank transfer or Mercado Pago"],
              images: [
                { src: "/work/mayma/screens/carrito.webp", alt: "Mayma cart with product variant, quantity and order summary", width: 2940, height: 1600 },
                { src: "/work/mayma/screens/checkout-entrega.webp", alt: "First checkout step for choosing pickup or Correo Argentino delivery", width: 2940, height: 1610 },
                { src: "/work/mayma/screens/checkout-pago-redacted.webp", alt: "Anonymised payment step with bank transfer and Mercado Pago", width: 1695, height: 928 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "06 / Administration",
              title: "Operations are managed from the same product.",
              text: "The dashboard supports store monitoring, product and variant management, and updates to fabrics available in the customiser. Commercial data, inventory values and identities have been hidden in these captures.",
              points: ["Operational overview", "Products, variants and availability", "Custom fabrics with image and status"],
              images: [
                { src: "/work/mayma/screens/admin-resumen-redacted.webp", alt: "Mayma admin dashboard with metrics and identities hidden", width: 1696, height: 927 },
                { src: "/work/mayma/screens/admin-productos-redacted.webp", alt: "Product management with prices, stock and identifiers hidden", width: 1696, height: 927 },
                { src: "/work/mayma/screens/admin-telas-redacted.webp", alt: "Fabric management for the customiser with the administrator email hidden", width: 1697, height: 927 },
              ],
              layout: "wide",
            },
          ],
          modulesLabel: "What we built",
          modules: ["Ecommerce and catalogue", "Bikini customiser", "Sizes, measurements and variants", "Stock management", "Cart and checkout", "Mercado Pago and bank transfer", "Correo Argentino and pickup", "Custom WhatsApp enquiry"],
          technologyLabel: "Technology and integrations",
          technologies: ["React", "Vite", "Neon PostgreSQL", "Mercado Pago", "Cloudinary", "Correo Argentino", "Vercel"],
          closing: "A store where direct purchase and product customisation coexist, each with the flow it needs.",
        },
        caseStudy: {
          statement: "Summer as an interface: light, flexible and always in motion.",
          challenge: "Mayma Bikinis needed to sell products with multiple size, colour and model combinations without turning the purchase into a cold form.",
          approach: "We built a visual experience where catalogue and customisation coexist. Editorial hierarchy keeps the product forward while the interface supports clear choices.",
          highlights: [
            { title: "Flexible catalogue", text: "Variants, stock and collections keep their visual rhythm." },
            { title: "Customisation", text: "Tops and bottoms can be matched through a guided experience." },
            { title: "Identity in motion", text: "Water, coral and deep green translate the brand's energy." },
          ],
          outcome: "A warm, expressive store ready to grow with every new collection.",
        },
      },
    ),
  },
  {
    slug: "cosas-de-casa", index: "05", name: "Cosas de Casa", client: "Cosas de Casa Juguetería", year: "2026",
    url: "https://www.cosasdecasajugueteria.com.ar/", featured: true,
    palette: { background: "#f7c9d8", foreground: "#4c4145", accent: "#c6f0de", muted: "#fff9f4" },
    cover: { src: "/work/cosas-de-casa/cover.png", alt: "Casa de muñecas y juguetes de Cosas de Casa", width: 2048, height: 1024 },
    gallery: [
      { src: "/work/cosas-de-casa/category-wood.jpeg", alt: "Casa de muñecas de madera de Cosas de Casa", width: 800, height: 1067 },
      { src: "/work/cosas-de-casa/category-tiny.jpeg", alt: "Pequeños juguetes de colores de Cosas de Casa", width: 1200, height: 800 },
      { src: "/work/cosas-de-casa/detail.jpeg", alt: "El local de Cosas de Casa", width: 1164, height: 2048 },
    ],
    copy: copy(
      {
        category: "Deco / Home / Juguetería / Ecommerce",
        description: "Una tienda de juguetes y objetos para el hogar con catálogo por mundos, variantes y pedidos preparados por WhatsApp.",
        services: ["Diseño UX / UI", "Catálogo y navegación", "Carrito y pedido por WhatsApp", "Administración de productos"],
        productCaseStudy: {
          lead: "Un catálogo online para explorar juguetes, regalos y objetos de hogar, armar un carrito y enviar el pedido por WhatsApp.",
          role: "Diseño de experiencia + desarrollo ecommerce",
          challengeTitle: "Ordenar una tienda llena de mundos distintos.",
          challenge: "Cosas de Casa reúne productos muy diferentes. La tienda necesitaba ayudar a descubrirlos por categorías y subcategorías, mostrar variantes y disponibilidad, y hacer que preparar un pedido fuera simple tanto para quien compra como para el equipo del local.",
          sections: [
            {
              eyebrow: "01 / Exploración del catálogo",
              title: "Cada mundo tiene una entrada clara.",
              text: "La navegación organiza el catálogo en familias reconocibles, como Mundo de madera, Mundo Bebote, Mundo Tiny, Escritorio feliz, Muñecas de tela, Equipaje divertido y Mini bazar. Las subcategorías permiten afinar la búsqueda sin convertir la tienda en una lista interminable.",
              points: ["Categorías y subcategorías", "Acceso directo a ofertas", "Navegación pensada para recorrer la variedad"],
            },
            {
              eyebrow: "02 / Producto y disponibilidad",
              title: "Variantes y opciones, en contexto.",
              text: "Cada ficha presenta imágenes, opciones de variante y disponibilidad. Cuando un producto no está disponible, se identifica con su estado; el sistema no comunica cantidades de inventario que no existen.",
              points: ["Imágenes y detalles del producto", "Selección de variantes", "Disponibilidad clara, sin inventario numérico"],
            },
            {
              eyebrow: "03 / Carrito y pedido",
              title: "Un pedido listo para seguir por WhatsApp.",
              text: "El carrito conserva los productos mientras se recorre la tienda y prepara un resumen para compartir por WhatsApp. La experiencia termina en una conversación con el comercio: no procesa pagos ni confirma una venta dentro del sitio.",
              points: ["Carrito persistido en el navegador", "Resumen de productos y variantes", "Pedido enviado mediante WhatsApp"],
            },
            {
              eyebrow: "04 / Gestión del catálogo",
              title: "La tienda puede actualizarse desde su propia administración.",
              text: "El panel concentra la gestión de productos y configuración. Las imágenes cargadas se almacenan en Cloudinary y el catálogo se conserva en la base de datos del proyecto.",
              points: ["Administración de productos y categorías", "Carga de imágenes a Cloudinary", "Catálogo y configuración en Neon"],
            },
          ],
          modulesLabel: "Qué construimos",
          modules: ["Catálogo por categorías", "Subcategorías", "Fichas de producto y variantes", "Estados de disponibilidad", "Carrito persistido", "Resumen de pedido por WhatsApp", "Panel de productos y configuración", "Carga de imágenes"],
          technologyLabel: "Tecnologías e integraciones",
          technologies: ["React", "Vite", "Tailwind CSS", "Neon PostgreSQL", "Cloudinary", "Vercel", "Zustand"],
          closing: "Una tienda para descubrir productos con libertad y transformar esa exploración en un pedido claro para conversar.",
        },
        caseStudy: {
          statement: "Una tienda que conserva la sensación de entrar, mirar y encontrar algo especial.",
          challenge: "La variedad era parte del encanto, pero necesitaba una estructura capaz de ordenar categorías y productos sin perder el tono humano del local.",
          approach: "Usamos la idea de casa como sistema de navegación. Los mundos de producto funcionan como habitaciones y el recorrido termina en una consulta simple.",
          highlights: [
            { title: "Mundos, no filtros", text: "Las categorías hablan el lenguaje de la tienda y facilitan explorar." },
            { title: "Consulta cuidada", text: "El carrito organiza productos antes de abrir una conversación real." },
            { title: "Historia visible", text: "La historia de la tienda suma confianza sin volverse corporativa." },
          ],
          outcome: "Una experiencia cálida y navegable que lleva el carácter boutique a cualquier pantalla.",
        },
      },
      {
        category: "Deco / Home / Toys / Ecommerce",
        description: "An online shop for toys and home goods, with category-led discovery, product variants and WhatsApp orders.",
        services: ["UX / UI design", "Catalogue and navigation", "Cart and WhatsApp orders", "Product management"],
        productCaseStudy: {
          lead: "An online catalogue for exploring toys, gifts and home goods, building a cart and sending an order through WhatsApp.",
          role: "Experience design + ecommerce development",
          challengeTitle: "Bringing order to a shop full of different worlds.",
          challenge: "Cosas de Casa brings together very different products. The shop needed to help people discover them through categories and subcategories, understand variants and availability, and make preparing an order simple for both customers and the store team.",
          sections: [
            {
              eyebrow: "01 / Catalogue discovery",
              title: "A clear way into every world.",
              text: "Navigation groups the catalogue into recognisable collections such as Wooden World, Baby Dolls, Tiny World, Happy Desk, Fabric Dolls, Fun Travel and Mini Bazaar. Subcategories make browsing more specific without turning the shop into a long list.",
              points: ["Categories and subcategories", "Direct access to offers", "Navigation built around the range"],
            },
            {
              eyebrow: "02 / Products and availability",
              title: "Variants and options, in context.",
              text: "Each product page presents its images, variant options and availability. Out-of-stock items are clearly marked; the system does not communicate inventory quantities it does not have.",
              points: ["Product images and details", "Variant selection", "Clear availability without numeric stock"],
            },
            {
              eyebrow: "03 / Cart and order",
              title: "An order ready to continue on WhatsApp.",
              text: "The cart keeps products together while people browse and prepares a summary to share through WhatsApp. The experience ends in a conversation with the shop; it does not process payments or confirm a sale on the website.",
              points: ["Cart persisted in the browser", "Product and variant summary", "Order sent through WhatsApp"],
            },
            {
              eyebrow: "04 / Catalogue management",
              title: "The shop can update its own catalogue.",
              text: "The admin panel brings product and configuration management together. Uploaded images are stored in Cloudinary and the catalogue is kept in the project's database.",
              points: ["Product and category management", "Image uploads to Cloudinary", "Catalogue and settings in Neon"],
            },
          ],
          modulesLabel: "What we built",
          modules: ["Category-led catalogue", "Subcategories", "Product pages and variants", "Availability states", "Persistent cart", "WhatsApp order summary", "Product and settings admin", "Image uploads"],
          technologyLabel: "Technology and integrations",
          technologies: ["React", "Vite", "Tailwind CSS", "Neon PostgreSQL", "Cloudinary", "Vercel", "Zustand"],
          closing: "A shop where people can browse freely and turn discovery into a clear order to discuss.",
        },
        caseStudy: {
          statement: "A shop that keeps the feeling of stepping in, looking around and finding something special.",
          challenge: "Variety was part of its charm, but it needed a structure that could organise categories and products without losing the shop's human tone.",
          approach: "We used the idea of a home as a navigation system. Product worlds become rooms and the journey ends in a simple conversation.",
          highlights: [
            { title: "Worlds, not filters", text: "Categories speak the shop's language and make exploration easier." },
            { title: "Considered enquiry", text: "The cart organises products before opening a real conversation." },
            { title: "A visible story", text: "The shop's story builds trust without becoming corporate." },
          ],
          outcome: "A warm, navigable experience that carries the boutique character to every screen.",
        },
      },
    ),
  },
  {
    slug: "xeneize-regaleria", index: "06", name: "Xeneize", client: "Xeneize Regalería", year: "2026",
    url: "https://www.xeneizeregaleria.com.ar/", featured: true,
    palette: { background: "#fc2daf", foreground: "#18121d", accent: "#ffd666", muted: "#fff7fb" },
    brandLogo: { src: "/work/xeneize/brand-logo.png", alt: "Logo de Xeneize Regalería", width: 1254, height: 1254, contrast: "dark" },
    cover: { src: "/work/xeneize/cover.jpg", alt: "Caja de regalo rosa con cinta dorada", width: 1600, height: 1067 },
    gallery: [
      { src: "/work/xeneize/logo-black.png", alt: "Wordmark de Xeneize Regalería", width: 1000, height: 1000 },
    ],
    copy: copy(
      {
        category: "Ecommerce / Regalería",
        description: "Una tienda online para descubrir regalos, elegir variantes, pagar y seguir el pedido hasta su entrega o retiro.",
        services: ["Diseño UX / UI", "Desarrollo ecommerce", "Checkout y pagos", "Operación de catálogo y pedidos"],
        productCaseStudy: {
          lead: "E-commerce con catálogo, variantes y stock, checkout con Mercado Pago o transferencia y gestión conectada de pedidos y entregas.",
          role: "Diseño de experiencia + desarrollo ecommerce",
          challengeTitle: "Hacer simple una compra con muchas piezas conectadas.",
          challenge: "La tienda necesitaba reunir descubrimiento de productos, variantes, disponibilidad, medios de pago y distintas formas de entrega. Al mismo tiempo, el equipo debía poder administrar catálogo y pedidos desde un solo lugar.",
          sections: [
            {
              eyebrow: "01 / Catálogo y descubrimiento",
              title: "Encontrar un regalo empieza por explorar.",
              text: "El catálogo organiza productos y categorías para que cada persona pueda descubrir opciones, consultar ofertas y llegar a la ficha que necesita antes de comprar.",
              points: ["Navegación de catálogo y categorías", "Ofertas y fichas de producto", "Imágenes y variantes en contexto"],
            },
            {
              eyebrow: "02 / Variantes y disponibilidad",
              title: "Cada elección se valida con el stock.",
              text: "Las variantes disponibles se seleccionan dentro de la ficha. El carrito vuelve a validar la disponibilidad antes de crear el pedido, para no continuar con una opción que ya no tiene stock.",
              points: ["Variantes por producto", "Stock revisado antes del pedido", "Carrito persistido mientras se compra"],
            },
            {
              eyebrow: "03 / Checkout y pagos",
              title: "Dos formas de completar la compra.",
              text: "El checkout reúne los datos del pedido y permite continuar con Mercado Pago Checkout Pro o registrar una transferencia manual. El estado final del pago vuelve a la tienda mediante la notificación de Mercado Pago.",
              points: ["Pedido con productos y entrega", "Mercado Pago Checkout Pro", "Transferencia manual y revisión del pago"],
            },
            {
              eyebrow: "04 / Entrega y seguimiento",
              title: "La gestión continúa después del pago.",
              text: "La compra puede continuar con opciones de Correo Argentino o retiro. El panel organiza pedidos, pagos y cambios de estado, y permite gestionar la comunicación operativa de envío o retiro.",
              points: ["Envío a domicilio o a sucursal", "Retiro en el local", "Pedidos y estados en administración"],
            },
            {
              eyebrow: "05 / Operación de la tienda",
              title: "Catálogo y pedidos en el mismo flujo de trabajo.",
              text: "La administración incluye productos, pedidos, cupones y configuración. Las imágenes se cargan a Cloudinary; las notificaciones transaccionales acompañan la aprobación del pago y las tareas de entrega.",
              points: ["Gestión de catálogo, pedidos y cupones", "Imágenes en Cloudinary", "Correos transaccionales con Resend"],
            },
          ],
          modulesLabel: "Qué construimos",
          modules: ["Catálogo y fichas", "Variantes y stock", "Carrito y checkout", "Mercado Pago Checkout Pro", "Transferencias manuales", "Envíos con Correo Argentino", "Retiro", "Gestión de pedidos", "Cupones", "Notificaciones transaccionales"],
          technologyLabel: "Tecnologías e integraciones",
          technologies: ["React", "Vite", "Tailwind CSS", "Supabase", "Zustand", "Mercado Pago", "Correo Argentino", "Cloudinary", "Vercel Functions", "Resend"],
          closing: "Una compra conectada de punta a punta: descubrir, elegir, pagar y coordinar la entrega.",
        },
        caseStudy: {
          statement: "Regalar debería sentirse fácil antes, durante y después de elegir.",
          challenge: "El catálogo necesitaba convivir con stock, variantes, pagos y operación diaria sin hacer visible la complejidad detrás de escena.",
          approach: "Diseñamos un recorrido comercial franco: descubrimiento, producto, carrito y pago. El rosa funciona como señal, no como decoración constante.",
          highlights: [
            { title: "Compra directa", text: "Menos fricción entre encontrar un producto y completar el pago." },
            { title: "Catálogo vivo", text: "Stock, variantes y ofertas se administran para el día a día." },
            { title: "Marca reconocible", text: "Tipografía editorial y color intenso convierten cada pantalla en Xeneize." },
          ],
          outcome: "Un ecommerce con personalidad que ordena la operación y mantiene la compra simple.",
        },
      },
      {
        category: "Ecommerce / Gifts",
        description: "An online shop for finding gifts, choosing variants, paying and following an order through delivery or pickup.",
        services: ["UX / UI design", "Ecommerce development", "Checkout and payments", "Catalogue and order operations"],
        productCaseStudy: {
          lead: "An ecommerce with product catalogue, variants and stock, checkout through Mercado Pago or bank transfer, and connected order and delivery management.",
          role: "Experience design + ecommerce development",
          challengeTitle: "Making a connected purchase feel simple.",
          challenge: "The shop needed to bring together product discovery, variants, availability, payment methods and different delivery options. The team also needed to manage its catalogue and orders from one place.",
          sections: [
            {
              eyebrow: "01 / Catalogue and discovery",
              title: "Finding a gift starts with exploring.",
              text: "The catalogue organises products and categories so people can discover options, browse offers and reach the product page they need before buying.",
              points: ["Catalogue and category navigation", "Offers and product pages", "Images and variants in context"],
            },
            {
              eyebrow: "02 / Variants and availability",
              title: "Each choice is checked against stock.",
              text: "Available variants are selected on the product page. The cart validates availability again before creating an order, so a choice that has sold out cannot proceed.",
              points: ["Product variants", "Stock checked before order creation", "Cart persisted during shopping"],
            },
            {
              eyebrow: "03 / Checkout and payments",
              title: "Two ways to complete the purchase.",
              text: "Checkout gathers the order details and lets customers continue through Mercado Pago Checkout Pro or register a manual bank transfer. Mercado Pago sends the final payment status back to the shop.",
              points: ["Order details and delivery", "Mercado Pago Checkout Pro", "Manual bank transfer and review"],
            },
            {
              eyebrow: "04 / Delivery and follow-up",
              title: "Order management continues after payment.",
              text: "An order can continue through Correo Argentino or local pickup. The admin panel organises orders, payments and status updates, including operational communication for shipping or pickup.",
              points: ["Home or branch delivery", "Local pickup", "Orders and status management"],
            },
            {
              eyebrow: "05 / Store operations",
              title: "Catalogue and orders in one workflow.",
              text: "The admin includes products, orders, coupons and settings. Images are uploaded to Cloudinary; transactional email supports approved payments and delivery or pickup operations.",
              points: ["Catalogue, order and coupon management", "Images on Cloudinary", "Transactional email through Resend"],
            },
          ],
          modulesLabel: "What we built",
          modules: ["Catalogue and product pages", "Variants and stock", "Cart and checkout", "Mercado Pago Checkout Pro", "Manual bank transfers", "Correo Argentino shipping", "Local pickup", "Order management", "Coupons", "Transactional notifications"],
          technologyLabel: "Technology and integrations",
          technologies: ["React", "Vite", "Tailwind CSS", "Supabase", "Zustand", "Mercado Pago", "Correo Argentino", "Cloudinary", "Vercel Functions", "Resend"],
          closing: "One connected purchase journey: discover, choose, pay and arrange delivery.",
        },
        caseStudy: {
          statement: "Giving should feel easy before, during and after choosing.",
          challenge: "The catalogue needed to coexist with stock, variants, payments and daily operations without exposing the complexity behind it.",
          approach: "We designed a direct commercial path: discovery, product, cart and payment. Pink works as a signal rather than constant decoration.",
          highlights: [
            { title: "Direct purchase", text: "Less friction between finding a product and completing payment." },
            { title: "Living catalogue", text: "Stock, variants and offers are ready for daily operations." },
            { title: "Recognisable brand", text: "Editorial type and intense colour make every screen feel like Xeneize." },
          ],
          outcome: "A distinctive ecommerce that organises operations while keeping the purchase simple.",
        },
      },
    ),
  },
  {
    slug: "sistema-odontologico-completo", index: "03", name: "Sistema Odontológico Completo", client: "Sistema Odontológico Completo", year: "2026",
    featured: true,
    palette: { background: "#f3f8f8", foreground: "#171916", accent: "#087f7d", muted: "#526267" },
    cover: { src: "/work/odontologia/cover-redacted.png", alt: "Captura del sistema odontológico en la pantalla de plan de tratamiento, con el DNI oculto", width: 1697, height: 927 },
    gallery: [],
    copy: copy(
      {
        category: "Sistema de gestión odontológica",
        description: "Una plataforma para centralizar pacientes, agenda, historia clínica, odontograma, tratamientos y gestión del consultorio.",
        services: ["Diseño de producto", "Desarrollo full stack", "Integración con Google Calendar"],
        productCaseStudy: {
          heroImage: { src: "/work/odontologia/od3-redacted.jpeg", alt: "Captura anonimizada del odontograma FDI dentro del sistema de gestión odontológica", width: 1600, height: 880 },
          lead: "Un sistema para centralizar pacientes, turnos, historia clínica, odontograma, tratamientos, pagos y gestión del consultorio.",
          role: "Diseño de producto + desarrollo full stack",
          challengeTitle: "La clínica, organizada en un solo lugar.",
          challenge: "El consultorio necesitaba reunir la información de pacientes y el trabajo diario del equipo en una herramienta común: agenda, historia clínica, tratamientos, presupuestos, pagos y administración, con acceso definido por rol.",
          sections: [
            {
              eyebrow: "01 / Pacientes",
              title: "Una ficha que conecta cada parte de la atención.",
              text: "La ficha reúne datos del paciente y da acceso a las áreas vinculadas a su seguimiento clínico y administrativo, desde la anamnesis y las evoluciones hasta tratamientos y pagos.",
              image: { src: "/work/odontologia/od2-redacted.jpeg", alt: "Ficha de paciente anonimizada, con datos personales ocultos y acceso a resumen, anamnesis, odontograma, tratamiento y pagos", width: 1600, height: 876 },
              caption: "Captura anonimizada del perfil del paciente.",
              points: ["Resumen y datos de contacto", "Anamnesis e historia clínica", "Tratamientos y pagos relacionados"],
              layout: "split",
            },
            {
              eyebrow: "02 / Odontograma",
              title: "El estado dental, registrado pieza por pieza.",
              text: "El odontograma FDI permite seleccionar una pieza dental y registrar condiciones por cara, distinguiendo el estado existente del tratamiento requerido o planificado. La vista abarca dentición permanente y temporal.",
              points: ["Registro por pieza y superficie", "Condiciones y estado clínico", "Seguimiento de tratamientos planificados"],
              layout: "split",
            },
            {
              eyebrow: "03 / Historia clínica",
              title: "Antecedentes y evoluciones dentro de la ficha.",
              text: "La anamnesis organiza factores de riesgo, antecedentes, medicación y observaciones clínicas. Los registros de historia y evolución quedan en el contexto del paciente y se muestran según los permisos del usuario.",
              image: { src: "/work/odontologia/od6-redacted.jpeg", alt: "Pantalla anonimizada de anamnesis con condiciones, factores de riesgo y antecedentes clínicos", width: 1600, height: 876 },
              caption: "Captura anonimizada de anamnesis.",
              points: ["Antecedentes y observaciones", "Condiciones y factores de riesgo", "Acceso regulado por permisos"],
              layout: "split",
            },
            {
              eyebrow: "04 / Tratamientos y presupuestos",
              title: "Del plan clínico a una propuesta ordenada.",
              text: "Los tratamientos se registran con profesional, pieza, fecha y estado. Desde el plan se puede preparar un presupuesto con conceptos del tratamiento o del catálogo, cantidades, importes y moneda.",
              image: { src: "/work/odontologia/od5-redacted.jpeg", alt: "Creador anonimizado de presupuestos vinculado al plan de tratamiento odontológico", width: 1600, height: 875 },
              caption: "Captura anonimizada del flujo de presupuesto.",
              points: ["Tratamientos por paciente y pieza dental", "Seguimiento de estados", "Presupuestos editables y documentos"],
              layout: "wide",
            },
            {
              eyebrow: "05 / Agenda y Google Calendar",
              title: "Una agenda conectada con los calendarios del consultorio.",
              text: "Google Calendar es la fuente de verdad de los turnos. Desde el sistema se consulta disponibilidad, se crean y actualizan citas y se sincronizan los eventos asociados a cada agenda o sillón.",
              points: ["Disponibilidad y turnos", "Calendarios asociados a consultorios", "Sincronización de eventos con Google Calendar"],
            },
            {
              eyebrow: "06 / Equipo y consultorios",
              title: "La operación se adapta al equipo de la clínica.",
              text: "La configuración organiza profesionales, consultorios y sillones. Los permisos diferencian las tareas de administración, odontología, recepción y asistencia para limitar cada acción a lo que necesita ese rol.",
              image: { src: "/work/odontologia/od1-redacted.jpeg", alt: "Configuración anonimizada de usuarios y roles de administrador, odontólogo, recepción y asistente", width: 1600, height: 874 },
              caption: "Captura anonimizada de usuarios, roles y permisos.",
              points: ["Administrador, odontólogo, recepción y asistente", "Profesionales y consultorios", "Acceso según permisos"],
              layout: "split",
            },
            {
              eyebrow: "07 / Gestión del consultorio",
              title: "La estructura física también forma parte del sistema.",
              text: "Los consultorios y sillones se configuran como recursos de trabajo y pueden asociarse con calendarios para organizar la agenda clínica.",
              image: { src: "/work/odontologia/od8-redacted.jpeg", alt: "Configuración anonimizada de consultorios y sillones en el sistema", width: 1600, height: 872 },
              caption: "Captura de configuración de consultorios.",
              layout: "split",
            },
            {
              eyebrow: "08 / Pagos y reportes",
              title: "Seguimiento administrativo con contexto.",
              text: "El sistema relaciona los pagos con el paciente y su tratamiento. Los reportes permiten revisar turnos, producción, cobros y saldos pendientes sin exponer indicadores de una clínica en esta presentación.",
              points: ["Registro e historial de pagos", "Cobros vinculados a pacientes", "Reportes de turnos y saldos"],
              layout: "split",
            },
          ],
          modulesLabel: "Módulos construidos",
          modules: ["Pacientes y ficha", "Agenda", "Google Calendar", "Odontograma FDI", "Historia clínica y anamnesis", "Tratamientos", "Presupuestos", "Pagos", "Profesionales", "Roles y permisos", "Archivos", "Reportes", "Configuración del consultorio"],
          technologyLabel: "Tecnologías e integraciones",
          technologies: ["React", "TypeScript", "Vite", "Hono", "Cloudflare Workers", "Neon PostgreSQL", "Drizzle ORM", "Google Calendar API", "Cloudinary"],
          closing: "Un sistema modular que reúne la atención clínica y la administración cotidiana del consultorio.",
        },
      },
      {
        category: "Custom system / Dentistry",
        description: "A platform that brings together patients, scheduling, clinical records, odontograms, treatments and practice management.",
        services: ["Product design", "Full-stack development", "Google Calendar integration"],
        productCaseStudy: {
          heroImage: { src: "/work/odontologia/od3-redacted.jpeg", alt: "Anonymised capture of the FDI odontogram in the dental management system", width: 1600, height: 880 },
          lead: "A system that brings together patients, appointments, clinical records, odontograms, treatments, payments and practice operations.",
          role: "Product design + full-stack development",
          challengeTitle: "The clinic, organised in one place.",
          challenge: "The practice needed to bring patient information and the team's daily work into a shared tool: appointments, clinical records, treatment plans, budgets, payments and administration, with access defined by role.",
          sections: [
            {
              eyebrow: "01 / Patients",
              title: "A patient record that connects each part of care.",
              text: "The record brings together patient details and links the areas used for clinical and administrative follow-up, from anamnesis and clinical notes to treatments and payments.",
              image: { src: "/work/odontologia/od2-redacted.jpeg", alt: "Anonymised patient record with personal details hidden and links to summary, anamnesis, odontogram, treatment and payments", width: 1600, height: 876 },
              caption: "Anonymised patient profile capture.",
              points: ["Summary and contact details", "Anamnesis and clinical history", "Related treatments and payments"],
              layout: "split",
            },
            {
              eyebrow: "02 / Odontogram",
              title: "Dental status, recorded tooth by tooth.",
              text: "The FDI odontogram lets a practitioner select a tooth and record conditions by surface, distinguishing an existing condition from treatment that is needed or planned. It covers both permanent and primary teeth.",
              points: ["Records by tooth and surface", "Clinical conditions and status", "Follow-up for planned treatments"],
              layout: "split",
            },
            {
              eyebrow: "03 / Clinical history",
              title: "Medical history and clinical notes in context.",
              text: "The anamnesis organises risk factors, medical history, medication and clinical observations. History and evolution records stay in the patient context and are shown according to user permissions.",
              image: { src: "/work/odontologia/od6-redacted.jpeg", alt: "Anonymised anamnesis screen with health conditions, risk factors and clinical history", width: 1600, height: 876 },
              caption: "Anonymised anamnesis capture.",
              points: ["Medical history and observations", "Conditions and risk factors", "Access controlled by permissions"],
              layout: "split",
            },
            {
              eyebrow: "04 / Treatments and budgets",
              title: "From a clinical plan to an organised estimate.",
              text: "Treatments are recorded with the professional, tooth, date and status. A budget can be prepared from a treatment plan or catalogue items, with adjustable quantities, amounts and currency.",
              image: { src: "/work/odontologia/od5-redacted.jpeg", alt: "Anonymised budget builder linked to a dental treatment plan", width: 1600, height: 875 },
              caption: "Anonymised budget workflow capture.",
              points: ["Treatments by patient and tooth", "Status tracking", "Editable budgets and documents"],
              layout: "wide",
            },
            {
              eyebrow: "05 / Scheduling and Google Calendar",
              title: "A schedule connected to the practice calendars.",
              text: "Google Calendar is the source of truth for appointments. The system checks availability, creates and updates appointments, and synchronises events linked to each schedule or dental chair.",
              points: ["Availability and appointments", "Calendars linked to operatories", "Google Calendar event synchronisation"],
            },
            {
              eyebrow: "06 / Team and operatories",
              title: "Operations shaped around the clinical team.",
              text: "Settings organise professionals, rooms and dental chairs. Permissions distinguish administration, dentist, reception and assistant tasks, limiting each action to what that role needs.",
              image: { src: "/work/odontologia/od1-redacted.jpeg", alt: "Anonymised user and role settings for administrator, dentist, reception and assistant", width: 1600, height: 874 },
              caption: "Anonymised users, roles and permissions capture.",
              points: ["Administrator, dentist, reception and assistant", "Professionals and operatories", "Permission-based access"],
              layout: "split",
            },
            {
              eyebrow: "07 / Practice management",
              title: "The physical setup is part of the system.",
              text: "Operatories and dental chairs are configured as work resources and can be associated with calendars to organise the clinic schedule.",
              image: { src: "/work/odontologia/od8-redacted.jpeg", alt: "Anonymised practice configuration for operatories and dental chairs", width: 1600, height: 872 },
              caption: "Operatory settings capture.",
              layout: "split",
            },
            {
              eyebrow: "08 / Payments and reports",
              title: "Administrative tracking with context.",
              text: "The system links payments to each patient and treatment. Reports help review appointments, production, collections and outstanding balances without exposing a clinic's private indicators in this presentation.",
              points: ["Payment records and history", "Collections linked to patients", "Appointment and balance reports"],
              layout: "split",
            },
          ],
          modulesLabel: "Modules built",
          modules: ["Patients and records", "Scheduling", "Google Calendar", "FDI odontogram", "Clinical history and anamnesis", "Treatments", "Budgets", "Payments", "Professionals", "Roles and permissions", "Files", "Reports", "Practice settings"],
          technologyLabel: "Technology and integrations",
          technologies: ["React", "TypeScript", "Vite", "Hono", "Cloudflare Workers", "Neon PostgreSQL", "Drizzle ORM", "Google Calendar API", "Cloudinary"],
          closing: "A modular system that brings clinical care and the daily administration of the practice together.",
        },
      },
    ),
  },
  {
    slug: "santa-dominga", index: "04", name: "Santa Dominga", client: "Estancia Santa Dominga", year: "2026",
    url: "https://arroz2.vercel.app/es#home", featured: true,
    palette: { background: "#173b28", foreground: "#f4ead4", accent: "#bfa36a", muted: "#b9c7b0" },
    brandLogo: { src: "/work/santa-dominga/brand-logo.png", alt: "Logo de Santa Dominga", width: 1898, height: 829, contrast: "light" },
    cover: { src: "/work/santa-dominga/cover.webp", alt: "Cultivo de arroz de Santa Dominga en Entre Ríos", width: 1200, height: 1600, position: "center 58%" },
    gallery: [
      { src: "/work/santa-dominga/origin.webp", alt: "Arroz de Santa Dominga sostenido frente al campo", width: 960, height: 1280 },
      { src: "/work/santa-dominga/product.webp", alt: "Paquete de arroz orgánico Santa Dominga", width: 720, height: 1200 },
      { src: "/work/santa-dominga/landscape.webp", alt: "Paisaje productivo de Santa Dominga", width: 960, height: 1280 },
    ],
    copy: copy(
      {
        category: "Brand website / Producto / Multilingual",
        description: "Un sitio multilingüe que presenta arroz orgánico, producción integrada, certificaciones y contacto comercial desde Entre Ríos.",
        services: ["Dirección digital", "Estrategia de contenido", "Desarrollo web", "Español, inglés y portugués"],
        productCaseStudy: {
          heroImage: { src: "/work/santa-dominga/screens/home.webp", alt: "Home de Santa Dominga sobre el cultivo de arroz orgánico en Tatutí, Entre Ríos", width: 1600, height: 874 },
          lead: "Una plataforma institucional y comercial para explicar el origen, la producción y dos líneas de arroz orgánico a compradores locales e internacionales.",
          role: "Dirección digital + estrategia de contenido + desarrollo web",
          challengeTitle: "Del origen del arroz a una propuesta comercial clara.",
          challenge: "Santa Dominga necesitaba presentar tanto el arroz paddy destinado a operaciones mayoristas como el arroz envasado para consumo. El sitio debía explicar cómo se producen, qué certificaciones respaldan su origen y cómo iniciar una consulta comercial, en tres idiomas.",
          sections: [
            {
              eyebrow: "01 / Productos",
              title: "Dos formatos, una misma producción orgánica.",
              text: "La propuesta diferencia el arroz paddy orgánico para compradores mayoristas y procesos industriales del arroz Guri envasado para consumo. Este último se presenta como largo fino, integral o pulido, en envase de 500 g o en formatos personalizados según el cliente.",
              points: ["Arroz paddy orgánico para operaciones comerciales", "Arroz Guri envasado para consumo", "Formato de 500 g o presentación personalizada"],
              image: { src: "/work/santa-dominga/product.webp", alt: "Paquete de arroz orgánico Santa Dominga presentado como producto envasado", width: 720, height: 1200 },
            },
            {
              eyebrow: "02 / Origen y producción",
              title: "El proceso empieza en Tatutí, Entre Ríos.",
              text: "El contenido conecta los establecimientos propios con el cultivo, el riego, la cosecha y el control de producción. Esa secuencia ayuda a explicar la integración y el seguimiento desde el origen sin depender de frases genéricas de marca.",
              points: ["Producción propia en Tatutí", "Cultivo orgánico y riego responsable", "Control directo y trazabilidad integral"],
              images: [
                { src: "/work/santa-dominga/screens/origen.webp", alt: "Presentación del origen de Santa Dominga con cultivo propio y ubicación en Entre Ríos", width: 1600, height: 875 },
                { src: "/work/santa-dominga/screens/proceso.webp", alt: "Galería del proceso productivo con cultivo y cosecha de arroz en Santa Dominga", width: 1600, height: 872 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "03 / Certificaciones y calidad",
              title: "La confianza se apoya en documentación real.",
              text: "La sección de certificaciones reúne documentación sobre la producción orgánica y sus estándares. La presentación distingue los respaldos USDA-NOP y SUE, y permite consultar los documentos incorporados al sitio.",
              points: ["Certificación USDA-NOP", "Seguimiento orgánico SUE", "Documentos consultables desde la web"],
              image: { src: "/work/santa-dominga/screens/certificaciones.webp", alt: "Sección de certificaciones con documentación USDA-NOP, Organic Integrity y SUE", width: 1600, height: 872 },
              layout: "wide",
            },
            {
              eyebrow: "04 / Mercados y consultas",
              title: "Una consulta comercial con el contexto necesario.",
              text: "El recorrido prepara a compradores mayoristas, importadores y distribuidores antes del contacto. El formulario reúne país, empresa y datos de la consulta para continuar una conversación comercial con información útil desde el primer mensaje.",
              points: ["Contenido para mercados nacionales e internacionales", "Formulario comercial directo", "Contexto para importadores y distribuidores"],
              image: { src: "/work/santa-dominga/screens/contacto-comercial.webp", alt: "Sección para mercados internacionales con propuesta comercial y formulario de consulta", width: 1600, height: 870 },
            },
            {
              eyebrow: "05 / Experiencia multilingüe",
              title: "La misma propuesta, disponible en tres idiomas.",
              text: "La arquitectura y la jerarquía se mantienen en español, inglés y portugués. Cada versión adapta navegación, títulos y contenido comercial para que compradores de distintos mercados recorran la misma historia sin perder contexto.",
              points: ["Español, inglés y portugués", "Navegación localizada", "Estructura consistente entre idiomas"],
              images: [
                { src: "/work/santa-dominga/screens/idioma-en.webp", alt: "Sección de origen de Santa Dominga en su versión en inglés", width: 1600, height: 875 },
                { src: "/work/santa-dominga/screens/idioma-pt.webp", alt: "Sección de origen de Santa Dominga en su versión en portugués", width: 1600, height: 872 },
              ],
              layout: "wide",
            },
          ],
          modulesLabel: "Qué construimos",
          modules: ["Presentación de arroz paddy", "Presentación del arroz envasado Guri", "Origen y proceso productivo", "Trazabilidad", "Certificaciones y documentos", "Información para mercados internacionales", "Sitio en tres idiomas", "Consulta comercial"],
          technologyLabel: "Tecnologías",
          technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion", "Lucide"],
          closing: "Un sitio que hace visible el recorrido del producto y facilita el siguiente paso comercial.",
        },
        caseStudy: {
          statement: "Una historia de origen que se lee igual de bien en el campo y en un mercado internacional.",
          challenge: "La propuesta debía presentar producción, certificaciones y oferta comercial a públicos diferentes sin fragmentar la identidad.",
          approach: "El paisaje funciona como hilo narrativo. La información técnica aparece cuando aporta confianza, con una arquitectura multilingüe para compradores internacionales.",
          highlights: [
            { title: "Origen primero", text: "La geografía y el proceso productivo construyen credibilidad desde el inicio." },
            { title: "Información precisa", text: "Productos y certificaciones se explican con jerarquía, sin ruido." },
            { title: "Tres idiomas", text: "Español, inglés y portugués comparten estructura y tono." },
          ],
          outcome: "Una presencia institucional serena capaz de hablar de territorio, producto y exportación en un solo recorrido.",
        },
      },
      {
        category: "Brand website / Product / Multilingual",
        description: "A multilingual website presenting organic rice, integrated production, certifications and commercial contact from Entre Ríos.",
        services: ["Digital direction", "Content strategy", "Web development", "Spanish, English and Portuguese"],
        productCaseStudy: {
          heroImage: { src: "/work/santa-dominga/screens/home.webp", alt: "Santa Dominga homepage about organic rice cultivation in Tatutí, Entre Ríos", width: 1600, height: 874 },
          lead: "An institutional and commercial platform explaining the origin, production and two organic rice product lines to local and international buyers.",
          role: "Digital direction + content strategy + web development",
          challengeTitle: "From the rice's origin to a clear commercial offer.",
          challenge: "Santa Dominga needed to present both paddy rice for wholesale operations and packaged rice for consumption. The website had to explain how they are produced, which certifications support their origin and how to begin a commercial enquiry, in three languages.",
          sections: [
            {
              eyebrow: "01 / Products",
              title: "Two formats, one organic production.",
              text: "The offer distinguishes organic paddy rice for wholesale buyers and industrial processes from packaged Guri rice for consumption. The latter is long-grain, available whole or polished, in 500 g packs or customised formats according to customer requirements.",
              points: ["Organic paddy rice for commercial operations", "Packaged Guri rice for consumption", "500 g or customised packaging"],
              image: { src: "/work/santa-dominga/product.webp", alt: "Packaged Santa Dominga organic rice product", width: 720, height: 1200 },
            },
            {
              eyebrow: "02 / Origin and production",
              title: "The process begins in Tatutí, Entre Ríos.",
              text: "The content connects the estate to cultivation, irrigation, harvest and production control. This sequence explains the integrated process and traceability from origin without relying on generic brand statements.",
              points: ["Own production in Tatutí", "Organic cultivation and responsible irrigation", "Direct control and full traceability"],
              images: [
                { src: "/work/santa-dominga/screens/origen.webp", alt: "Santa Dominga origin page showing its own production and Entre Ríos location", width: 1600, height: 875 },
                { src: "/work/santa-dominga/screens/proceso.webp", alt: "Production gallery showing rice cultivation and harvest at Santa Dominga", width: 1600, height: 872 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "03 / Certifications and quality",
              title: "Trust supported by real documentation.",
              text: "The certifications section gathers documentation on organic production and its standards. It distinguishes USDA-NOP and SUE credentials and lets visitors consult the documents included on the website.",
              points: ["USDA-NOP certification", "SUE organic monitoring", "Documents available on the website"],
              image: { src: "/work/santa-dominga/screens/certificaciones.webp", alt: "Certifications section with USDA-NOP, Organic Integrity and SUE documentation", width: 1600, height: 872 },
              layout: "wide",
            },
            {
              eyebrow: "04 / Markets and enquiries",
              title: "A commercial enquiry with the right context.",
              text: "The journey prepares wholesalers, importers and distributors before contact. The form gathers country, company and enquiry details so the commercial conversation starts with useful information.",
              points: ["Content for local and international markets", "Direct commercial enquiry form", "Context for importers and distributors"],
              image: { src: "/work/santa-dominga/screens/contacto-comercial.webp", alt: "International markets section with commercial proposition and enquiry form", width: 1600, height: 870 },
            },
            {
              eyebrow: "05 / Multilingual experience",
              title: "The same proposition in three languages.",
              text: "The architecture and hierarchy remain consistent in Spanish, English and Portuguese. Each version localises navigation, headings and commercial content so buyers in different markets can follow the same story without losing context.",
              points: ["Spanish, English and Portuguese", "Localised navigation", "Consistent structure across languages"],
              images: [
                { src: "/work/santa-dominga/screens/idioma-en.webp", alt: "Santa Dominga origin section in English", width: 1600, height: 875 },
                { src: "/work/santa-dominga/screens/idioma-pt.webp", alt: "Santa Dominga origin section in Portuguese", width: 1600, height: 872 },
              ],
              layout: "wide",
            },
          ],
          modulesLabel: "What we built",
          modules: ["Paddy rice presentation", "Packaged Guri rice presentation", "Origin and production process", "Traceability", "Certifications and documents", "International market information", "Three-language website", "Commercial enquiry"],
          technologyLabel: "Technology",
          technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Framer Motion", "Lucide"],
          closing: "A website that makes the product journey visible and supports the next commercial step.",
        },
        caseStudy: {
          statement: "An origin story that reads just as well in the field as in an international market.",
          challenge: "The website had to present production, certifications and commercial offer to different audiences without fragmenting the identity.",
          approach: "The landscape is the narrative thread. Technical information appears where it builds trust, within a multilingual architecture for international buyers.",
          highlights: [
            { title: "Origin first", text: "Geography and production build credibility from the start." },
            { title: "Precise information", text: "Products and certifications are explained with hierarchy and no noise." },
            { title: "Three languages", text: "Spanish, English and Portuguese share structure and tone." },
          ],
          outcome: "A calm institutional presence that connects territory, product and export in one journey.",
        },
      },
    ),
  },
  {
    slug: "uruguai-yerba-mate", index: "02", name: "Uruguaí", client: "Uruguaí Yerba Mate", year: "2026",
    url: "https://yerbamateuruguai.com/", featured: true,
    palette: { background: "#394736", foreground: "#f7f1e2", accent: "#b99655", muted: "#c7c6a6" },
    brandLogo: { src: "/work/uruguai/brand-logo.png", alt: "Logo de Uruguaí Yerba Mate", width: 1916, height: 821, contrast: "light" },
    cover: { src: "/work/uruguai/cover-portada.jpg", alt: "Paquetes de yerba mate Uruguaí sobre una mesa de madera", width: 2803, height: 1869 },
    gallery: [
      { src: "/work/uruguai/variety.webp", alt: "Paquete de yerba mate Uruguaí Tradicional", width: 800, height: 1000 },
      { src: "/work/uruguai/product.webp", alt: "Paquete de yerba mate Uruguaí Premium", width: 640, height: 1160 },
      { src: "/work/uruguai/gran-oro.png", alt: "Reconocimiento Gran Oro de Uruguaí", width: 1000, height: 1000 },
    ],
    copy: copy(
      {
        category: "Ecosistema digital / Institucional + Ecommerce",
        description: "Dos sitios conectados para presentar la marca, vender online y acompañar sus campañas con contenido siempre actualizado.",
        services: ["UX / UI", "Desarrollo web", "Tiendanube", "Mantenimiento continuo"],
        productCaseStudy: {
          heroImage: { src: "/work/uruguai/screens/institucional-home.webp", alt: "Home del sitio institucional de Uruguaí, con presentación de marca y acceso para distribuidores", width: 2000, height: 1092 },
          lead: "Un ecosistema digital de dos sitios: una experiencia institucional para construir marca y una tienda sobre Tiendanube para vender, activar campañas y encontrar puntos de venta.",
          role: "Diseño, desarrollo y mantenimiento del ecosistema digital",
          challengeTitle: "Una marca en movimiento necesitaba más que una sola web.",
          challenge: "Uruguaí necesitaba presentar su historia y sus variedades, abrir un canal comercial para distribuidores y vender online. La solución se organizó en dos experiencias conectadas que Lufinha mantiene activas con novedades, productos, banners y acciones ligadas a cada campaña.",
          sections: [
            {
              eyebrow: "01 / Ecosistema digital",
              title: "Dos sitios, una misma presencia de marca.",
              text: "El sitio institucional concentra historia, producto, novedades y contacto comercial. La tienda resuelve catálogo y compra. Los dos comparten códigos visuales y se actualizan como partes de una misma estrategia digital.",
              points: ["Sitio institucional", "Ecommerce sobre Tiendanube", "Identidad y navegación conectadas"],
              images: [
                { src: "/work/uruguai/screens/institucional-historia.webp", alt: "Página institucional que presenta la historia y el origen entrerriano de Uruguaí", width: 2000, height: 1091 },
                { src: "/work/uruguai/screens/tienda-home.webp", alt: "Home del ecommerce de Uruguaí con banner de campaña de primavera", width: 2000, height: 1089 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "02 / Sitio institucional",
              title: "Producto, origen y posicionamiento comercial.",
              text: "La experiencia institucional explica el padrón uruguayo, presenta las variedades y ordena la historia de la marca. El contenido combina información de producto con argumentos para consumidores y potenciales distribuidores.",
              points: ["Historia y propuesta de marca", "Variedades y presentaciones", "Canal para distribuidores"],
              image: { src: "/work/uruguai/screens/institucional-productos.webp", alt: "Catálogo institucional con las variedades Premium, Tradicional y Suave de Uruguaí", width: 2000, height: 1092 },
            },
            {
              eyebrow: "03 / Contenido vivo",
              title: "La web acompaña lo que pasa con la marca.",
              text: "El trabajo continúa después del lanzamiento. Actualizamos novedades, productos, piezas destacadas y banners para que eventos, prensa, acciones deportivas y campañas comerciales también tengan presencia en los sitios.",
              points: ["Carga y edición de novedades", "Actualización de productos y banners", "Acompañamiento de campañas de marketing"],
              image: { src: "/work/uruguai/screens/institucional-novedades.webp", alt: "Sección de novedades de Uruguaí con contenidos de eventos, prensa y deporte", width: 2000, height: 1093 },
              layout: "wide",
            },
            {
              eyebrow: "04 / Canal mayorista",
              title: "La comunicación también abre oportunidades comerciales.",
              text: "El sitio institucional no termina en una presentación de marca. Incluye un recorrido específico para distribuidores y comercios, con un formulario directo que reúne los datos necesarios para iniciar una conversación comercial.",
              points: ["Mensaje específico para mayoristas", "Formulario de contacto", "Acceso visible desde la navegación"],
              image: { src: "/work/uruguai/screens/institucional-contacto.webp", alt: "Formulario institucional de contacto para comercios y distribuidores mayoristas", width: 2000, height: 1093 },
            },
            {
              eyebrow: "05 / Ecommerce en Tiendanube",
              title: "Una plataforma elegida por el cliente, llevada a la identidad Uruguaí.",
              text: "Por elección del cliente, el ecommerce funciona sobre Tiendanube. Sobre esa base trabajamos la experiencia visual, la organización del catálogo y las pantallas de producto para que la compra conserve el carácter de la marca.",
              points: ["Personalización visual de Tiendanube", "Catálogo de productos y combos", "Ficha de producto con opciones de presentación"],
              images: [
                { src: "/work/uruguai/screens/tienda-catalogo.webp", alt: "Catálogo del ecommerce con variedades, combos y accesorios de Uruguaí", width: 2000, height: 1092 },
                { src: "/work/uruguai/screens/tienda-producto.webp", alt: "Ficha de un combo de Uruguaí con tamaño, precio, cantidad y acción de compra", width: 2000, height: 1090 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "06 / Flujo de compra",
              title: "Del producto al carrito sin perder contexto.",
              text: "La tienda permite recorrer productos y combos, seleccionar opciones, ajustar cantidades y revisar el pedido en un carrito lateral antes de iniciar la compra. Las campañas activas también se reflejan dentro del flujo.",
              points: ["Selección de opciones y cantidades", "Carrito lateral", "Promociones integradas a la experiencia"],
              image: { src: "/work/uruguai/screens/tienda-carrito.webp", alt: "Carrito lateral del ecommerce con un combo, cantidad, subtotal y acceso para iniciar la compra", width: 2000, height: 1094 },
            },
            {
              eyebrow: "07 / Dónde comprar",
              title: "Encontrar Uruguaí cerca, aunque la compra no sea online.",
              text: "Desarrollamos dentro de la tienda un buscador de puntos de venta con mapa, listado y filtros. La persona puede buscar por comercio, ciudad o provincia, ver resultados relacionados y abrir WhatsApp o indicaciones para llegar.",
              points: ["Búsqueda por comercio, ciudad o provincia", "Mapa sincronizado con el listado", "Accesos a WhatsApp y cómo llegar"],
              images: [
                { src: "/work/uruguai/screens/tienda-mapa-general.webp", alt: "Vista general del buscador de puntos de venta de Uruguaí con listado y mapa", width: 2000, height: 1092 },
                { src: "/work/uruguai/screens/tienda-mapa-busqueda.webp", alt: "Resultados del mapa después de buscar puntos de venta en Entre Ríos", width: 2000, height: 1088 },
              ],
              layout: "wide",
            },
          ],
          modulesLabel: "Qué construimos y mantenemos",
          modules: ["Sitio institucional", "Ecommerce sobre Tiendanube", "Sistema visual compartido", "Catálogo y fichas de producto", "Contenido editorial y novedades", "Banners y campañas", "Canal para distribuidores", "Buscador de puntos de venta", "Mapa y filtros geográficos", "Mantenimiento continuo"],
          technologyLabel: "Plataformas y alcance",
          technologies: ["Desarrollo web a medida", "Tiendanube", "Mapa interactivo", "Gestión de contenidos", "Mantenimiento evolutivo"],
          closing: "Dos experiencias que crecen con la marca: una construye contexto y confianza; la otra convierte ese interés en compra y presencia territorial.",
          links: [
            { label: "Ver sitio institucional", href: "https://yerbamateuruguai.com/" },
            { label: "Ver tienda online", href: "https://tiendauruguai.com/" },
          ],
        },
        caseStudy: {
          statement: "Dos sitios conectados para construir marca, vender y acompañar cada campaña.",
          challenge: "Uruguaí tenía producto, historia y reconocimiento; el sitio debía reunirlos y facilitar el descubrimiento de variedades y el contacto comercial.",
          approach: "Llevamos los códigos del paquete —verde, oro y geometría— a una narrativa pausada, con producto protagonista y contenido sobre el padrón uruguayo.",
          highlights: [
            { title: "Familia de producto", text: "Variedades y presentaciones se comparan con claridad visual." },
            { title: "Calidad demostrada", text: "El reconocimiento Gran Oro y el proceso aparecen como evidencia." },
            { title: "Contenido que perdura", text: "Novedades y distribuidores extienden la utilidad del sitio." },
          ],
          outcome: "Un sitio con el peso de la marca y la calidez del ritual, útil para consumidores y distribuidores.",
        },
      },
      {
        category: "Digital ecosystem / Institutional + Ecommerce",
        description: "Two connected websites that present the brand, sell online and support its campaigns with continuously updated content.",
        services: ["UX / UI", "Web development", "Tiendanube", "Ongoing maintenance"],
        productCaseStudy: {
          heroImage: { src: "/work/uruguai/screens/institucional-home.webp", alt: "Uruguaí institutional homepage with brand introduction and distributor access", width: 2000, height: 1092 },
          lead: "A two-site digital ecosystem: an institutional experience for building the brand and a Tiendanube store for selling, running campaigns and finding stockists.",
          role: "Design, development and ongoing digital maintenance",
          challengeTitle: "A growing brand needed more than one website.",
          challenge: "Uruguaí needed to present its story and product range, open a commercial channel for distributors and sell online. The solution became two connected experiences that Lufinha keeps active through news, products, banners and campaign updates.",
          sections: [
            {
              eyebrow: "01 / Digital ecosystem",
              title: "Two sites, one consistent brand presence.",
              text: "The institutional site brings together story, products, news and commercial contact. The store handles catalogue and purchase. Both share visual codes and evolve as parts of one digital strategy.",
              points: ["Institutional website", "Ecommerce on Tiendanube", "Connected identity and navigation"],
              images: [
                { src: "/work/uruguai/screens/institucional-historia.webp", alt: "Institutional page presenting Uruguaí's story and Entre Ríos origin", width: 2000, height: 1091 },
                { src: "/work/uruguai/screens/tienda-home.webp", alt: "Uruguaí ecommerce homepage with a spring campaign banner", width: 2000, height: 1089 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "02 / Institutional site",
              title: "Product, origin and commercial positioning.",
              text: "The institutional experience explains the Uruguayan-style yerba, presents each variety and organises the brand story. Content balances product information with useful context for consumers and potential distributors.",
              points: ["Brand story and proposition", "Varieties and formats", "Distributor channel"],
              image: { src: "/work/uruguai/screens/institucional-productos.webp", alt: "Institutional catalogue showing Uruguaí Premium, Traditional and Suave varieties", width: 2000, height: 1092 },
            },
            {
              eyebrow: "03 / Living content",
              title: "The websites move with the brand.",
              text: "The work continues after launch. We update news, products, featured content and banners so events, press, sports activities and commercial campaigns also have a place across the digital experience.",
              points: ["News publishing and editing", "Product and banner updates", "Support for marketing campaigns"],
              image: { src: "/work/uruguai/screens/institucional-novedades.webp", alt: "Uruguaí news section with event, press and sports stories", width: 2000, height: 1093 },
              layout: "wide",
            },
            {
              eyebrow: "04 / Wholesale channel",
              title: "Communication also creates commercial opportunities.",
              text: "The institutional site goes beyond a brand presentation. It includes a dedicated path for distributors and retailers, with a direct form that gathers the information needed to start a commercial conversation.",
              points: ["Wholesale-specific message", "Contact form", "Visible access from navigation"],
              image: { src: "/work/uruguai/screens/institucional-contacto.webp", alt: "Institutional contact form for wholesale retailers and distributors", width: 2000, height: 1093 },
            },
            {
              eyebrow: "05 / Ecommerce on Tiendanube",
              title: "A client-chosen platform shaped around Uruguaí.",
              text: "The client chose Tiendanube for ecommerce. On top of that foundation, we worked on the visual experience, catalogue organisation and product pages so the purchase journey keeps the brand's character.",
              points: ["Tiendanube visual customisation", "Product and bundle catalogue", "Product pages with format options"],
              images: [
                { src: "/work/uruguai/screens/tienda-catalogo.webp", alt: "Ecommerce catalogue with Uruguaí varieties, bundles and accessories", width: 2000, height: 1092 },
                { src: "/work/uruguai/screens/tienda-producto.webp", alt: "Uruguaí bundle page with format, price, quantity and purchase action", width: 2000, height: 1090 },
              ],
              layout: "wide",
            },
            {
              eyebrow: "06 / Purchase flow",
              title: "From product to cart without losing context.",
              text: "The store lets people browse products and bundles, select options, adjust quantities and review the order in a side cart before starting checkout. Active campaigns also carry through the purchase experience.",
              points: ["Options and quantity selection", "Side cart", "Campaign incentives within the journey"],
              image: { src: "/work/uruguai/screens/tienda-carrito.webp", alt: "Ecommerce side cart with bundle, quantity, subtotal and checkout action", width: 2000, height: 1094 },
            },
            {
              eyebrow: "07 / Where to buy",
              title: "Find Uruguaí nearby, even when the purchase is offline.",
              text: "We developed a stockist finder within the store with a map, list and filters. People can search by shop, city or province, browse matching results and open WhatsApp or directions.",
              points: ["Search by shop, city or province", "Map synchronised with the result list", "WhatsApp and directions access"],
              images: [
                { src: "/work/uruguai/screens/tienda-mapa-general.webp", alt: "Overview of the Uruguaí stockist finder with list and map", width: 2000, height: 1092 },
                { src: "/work/uruguai/screens/tienda-mapa-busqueda.webp", alt: "Map results after searching for Uruguaí stockists in Entre Ríos", width: 2000, height: 1088 },
              ],
              layout: "wide",
            },
          ],
          modulesLabel: "What we build and maintain",
          modules: ["Institutional website", "Ecommerce on Tiendanube", "Shared visual system", "Catalogue and product pages", "Editorial content and news", "Banners and campaigns", "Distributor channel", "Stockist finder", "Map and geographic filters", "Ongoing maintenance"],
          technologyLabel: "Platforms and scope",
          technologies: ["Custom web development", "Tiendanube", "Interactive map", "Content management", "Ongoing improvements"],
          closing: "Two experiences that grow with the brand: one builds context and trust; the other turns that interest into purchase and local presence.",
          links: [
            { label: "Visit institutional site", href: "https://yerbamateuruguai.com/" },
            { label: "Visit online store", href: "https://tiendauruguai.com/" },
          ],
        },
        caseStudy: {
          statement: "Two connected websites for building the brand, selling and supporting every campaign.",
          challenge: "Uruguaí had product, story and recognition; the site needed to bring them together and make varieties and commercial contact easy to discover.",
          approach: "We translated the package codes —green, gold and geometry— into a calm narrative with the product and Uruguayan profile at its core.",
          highlights: [
            { title: "Product family", text: "Varieties and formats compare with visual clarity." },
            { title: "Proven quality", text: "The Gran Oro award and the process appear as evidence." },
            { title: "Lasting content", text: "News and distributors extend the site's usefulness." },
          ],
          outcome: "A site with the brand's weight and the ritual's warmth, useful to consumers and distributors.",
        },
      },
    ),
  },
];

const projectOrder = ["mayma-bikinis", "uruguai-yerba-mate", "sistema-odontologico-completo", "santa-dominga", "cosas-de-casa", "xeneize-regaleria"];
const projectOrderIndex = new Map(projectOrder.map((slug, index) => [slug, index]));
export const projects = projectEntries.slice().sort((a, b) => (projectOrderIndex.get(a.slug) ?? Number.MAX_SAFE_INTEGER) - (projectOrderIndex.get(b.slug) ?? Number.MAX_SAFE_INTEGER));

export const featuredProjects = projects.filter((project) => project.featured);

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}

export function getLocalizedProject(project: Project, locale: Locale): LocalizedProject {
  const { copy: translations, ...base } = project;
  return { ...base, ...translations[locale] };
}

export function getLocalizedProjects(locale: Locale) {
  return projects.map((project) => getLocalizedProject(project, locale));
}
