import type { Locale } from "@/types/project";

export const studioContent = {
  es: {
    navigation: { home: "Inicio", work: "Trabajo", studio: "Estudio", contact: "Contacto", menu: "Menú", close: "Cerrar" },
    hero: {
      eyebrow: "Estudio independiente · Entre Ríos",
      title: "Diseñamos y construimos lo que tu negocio necesita.",
      description: "Somos Rafa y Luca. Creamos páginas web, tiendas online y sistemas a medida, acompañándote desde la idea hasta que está funcionando de verdad.",
      primaryCta: "Ver nuestro trabajo",
      secondaryCta: "Contanos tu idea",
      scroll: "Ver el trabajo",
    },
    manifesto: {
      eyebrow: "Nuestra práctica",
      before: "No hacemos sitios para mirar.",
      after: "Construimos sitios para recorrer, elegir y recordar.",
    },
    work: {
      eyebrow: "Proyectos / 06",
      title: "Algunos proyectos que hicimos.",
      description: "Páginas, tiendas y sistemas hechos para resolver necesidades reales.",
      live: "Vista del proyecto",
      open: "Ver proyecto",
      visit: "Visitar web",
      all: "Ver todos los proyectos",
      count: "proyectos",
    },
    interlude: {
      eyebrow: "Más que páginas",
      title: "Catálogos, producto, checkout, contenido y gesto.",
      body: "Diseñamos el sistema completo para que cada interacción siga hablando el idioma de la marca.",
    },
    services: {
      eyebrow: "Lufinha Studio / Diseño + desarrollo digital",
      title: "Qué hacemos.",
      statement: "El alcance justo para cada proyecto.",
      intro: "No todo negocio necesita lo mismo. Lo pensamos con vos y construimos lo que realmente hace falta.",
      signature: "Rafa + Luca detrás de cada proyecto.",
      items: [
        { title: "Páginas web", focus: "Presencia digital", text: "Una web clara, atractiva y fácil de recorrer para que quien llega entienda por qué elegirte.", fit: "Para mostrar tu marca, explicar lo que hacés y recibir consultas.", cta: "Hablemos de tu web" },
        { title: "Tiendas online", focus: "Compra online", text: "Una experiencia de compra sencilla y con personalidad, desde el primer producto hasta el checkout.", fit: "Para vender productos online con catálogo, pagos y envíos bien resueltos.", cta: "Hablemos de tu tienda" },
        { title: "Sistemas a medida", focus: "Herramientas propias", text: "Herramientas diseñadas alrededor de tu manera de trabajar, cuando una página tradicional no alcanza.", fit: "Para ordenar procesos, gestionar información o crear un producto digital propio.", cta: "Hablemos de tu idea" },
      ],
    },
    process: {
      eyebrow: "Cómo trabajamos",
      title: "De la primera charla a algo que ya está funcionando.",
      steps: [
        { title: "Te escuchamos", text: "Nos contás qué necesitás, qué tenés hoy y qué querés conseguir." },
        { title: "Lo pensamos juntos", text: "Definimos la estructura, el diseño y cómo debería funcionar." },
        { title: "Lo construimos", text: "Diseñamos y desarrollamos el proyecto trabajando sobre versiones reales." },
        { title: "Lo ponemos en marcha", text: "Publicamos, probamos y dejamos todo funcionando." },
      ],
    },
    capabilities: {
      eyebrow: "Lo que hacemos",
      title: "Del primer mapa al último pixel en producción.",
      items: ["Dirección digital", "UX / UI", "Creative development", "Ecommerce", "Motion & interaction", "Sistemas de contenido"],
      stack: "Tecnología que queda detrás de la experiencia",
    },
    stack: {
      eyebrow: "Tecnologías / herramientas",
      title: "Con qué trabajamos.",
      description: "Elegimos las herramientas según lo que necesita cada proyecto. Estas son algunas de las tecnologías que usamos habitualmente para diseñar, desarrollar y poner productos en producción.",
      groups: [
        { title: "Frontend", items: ["React", "React Native", "TypeScript", "JavaScript", "Next.js"] },
        { title: "Backend / datos", items: ["Node.js", "PostgreSQL", "Neon", "APIs / REST"] },
        { title: "Infraestructura", items: ["Vercel", "Docker", "Cloudinary", "Git", "GitHub"] },
      ],
    },
    studio: {
      eyebrow: "El estudio",
      title: "Somos Rafa y Luca.",
      body: "Somos un estudio de diseño y desarrollo. Vas a hablar directamente con quienes piensan y hacen el trabajo.",
      people: "Las personas detrás del trabajo",
      shortBios: {
        Rafa: "Soy curiosa, creativa y obsesiva con los detalles. Bajo ideas a tierra y busco ese equilibrio entre que algo se vea lindo y funcione de verdad.",
        Luca: "Estudio Sistemas y disfruto crear cosas desde cero. Me interesan el desarrollo, la tecnología y especialmente la ciberseguridad.",
      },
    },
    contact: {
      eyebrow: "¿Tenés una idea?",
      title: "Contanos qué tenés en mente.",
      body: "No hace falta que tengas todo definido. Compartinos la idea y la pensamos juntos.",
      cta: "Hablemos de tu proyecto",
      direct: "Contacto directo",
      response: "Leemos cada consulta personalmente.",
    },
    common: {
      selectedWork: "Trabajo seleccionado",
      viewProject: "Ver proyecto",
      visitSite: "Visitar sitio",
      next: "Siguiente proyecto",
      allProjects: "Todos los proyectos",
      allWork: "Volver a Trabajo",
      challenge: "Qué necesitaban",
      approach: "Qué hicimos",
      decisions: "Decisiones clave",
      result: "El resultado",
      projectType: "Tipo de proyecto",
    },
  },
  en: {
    navigation: { home: "Home", work: "Work", studio: "Studio", contact: "Contact", menu: "Menu", close: "Close" },
    hero: {
      eyebrow: "Independent studio · Entre Ríos",
      title: "We design and build what your business needs.",
      description: "We're Rafa and Luca. We make websites, online stores and custom systems, guiding you from the first idea to something that is working for real.",
      primaryCta: "See our work",
      secondaryCta: "Tell us your idea",
      scroll: "See the work",
    },
    manifesto: {
      eyebrow: "Our practice",
      before: "We do not make sites to look at.",
      after: "We build sites to explore, choose and remember.",
    },
    work: {
      eyebrow: "Work / 06",
      title: "Some projects we've made.",
      description: "Websites, stores and systems made to solve real needs.",
      live: "Project preview",
      open: "View project",
      visit: "Visit website",
      all: "See all projects",
      count: "projects",
    },
    interlude: {
      eyebrow: "Beyond pages",
      title: "Catalogues, product, checkout, content and gesture.",
      body: "We design the complete system so every interaction keeps speaking the brand's language.",
    },
    services: {
      eyebrow: "Lufinha Studio / Digital design + development",
      title: "What we do.",
      statement: "The right scope for each project.",
      intro: "Every business needs something different. We think it through with you and build what the project actually needs.",
      signature: "Rafa + Luca behind every project.",
      items: [
        { title: "Websites", focus: "Digital presence", text: "A clear, appealing website that is easy to explore, so visitors understand why they should choose you.", fit: "For showing your brand, explaining what you do and receiving enquiries.", cta: "Talk about your website" },
        { title: "Online stores", focus: "Online shopping", text: "A simple shopping experience with your brand's personality, from the first product to checkout.", fit: "For selling products online with catalogue, payments and shipping thoughtfully handled.", cta: "Talk about your store" },
        { title: "Custom systems", focus: "Your own tools", text: "Tools designed around the way you work when a traditional website cannot do the job.", fit: "For organising processes, managing information or building your own digital product.", cta: "Talk about your idea" },
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "From the first conversation to something that works.",
      steps: [
        { title: "We listen", text: "You tell us what you need, what you have today and what you want to achieve." },
        { title: "We think it through together", text: "We define the structure, the design and how it should work." },
        { title: "We build it", text: "We design and develop the project using real working versions." },
        { title: "We get it running", text: "We publish, test and make sure everything works." },
      ],
    },
    capabilities: {
      eyebrow: "What we do",
      title: "From the first map to the last pixel in production.",
      items: ["Digital direction", "UX / UI", "Creative development", "Ecommerce", "Motion & interaction", "Content systems"],
      stack: "Technology that stays behind the experience",
    },
    stack: {
      eyebrow: "Technology / tools",
      title: "What we work with.",
      description: "We choose tools around what each project needs. These are some of the technologies we regularly use to design, build and take products into production.",
      groups: [
        { title: "Frontend", items: ["React", "React Native", "TypeScript", "JavaScript", "Next.js"] },
        { title: "Backend / data", items: ["Node.js", "PostgreSQL", "Neon", "APIs / REST"] },
        { title: "Infrastructure", items: ["Vercel", "Docker", "Cloudinary", "Git", "GitHub"] },
      ],
    },
    studio: {
      eyebrow: "The studio",
      title: "We're Rafa and Luca.",
      body: "We're a design and development studio. You'll speak directly with the people thinking through and doing the work.",
      people: "The people behind the work",
      shortBios: {
        Rafa: "I'm curious, creative and focused on details. I turn ideas into something real and look for the balance between a good look and a good result.",
        Luca: "I study systems and enjoy building things from scratch. I'm interested in development, technology and especially cybersecurity.",
      },
    },
    contact: {
      eyebrow: "Have an idea?",
      title: "Tell us what you have in mind.",
      body: "You don't need to have it all figured out. Share the idea and we'll think it through together.",
      cta: "Let's talk about your project",
      direct: "Direct contact",
      response: "We read every enquiry ourselves.",
    },
    common: {
      selectedWork: "Selected work",
      viewProject: "View project",
      visitSite: "Visit website",
      next: "Next project",
      allProjects: "All projects",
      allWork: "Back to Work",
      challenge: "What they needed",
      approach: "What we did",
      decisions: "Key decisions",
      result: "The result",
      projectType: "Project type",
    },
  },
} satisfies Record<Locale, object>;

export function getStudioContent(locale: Locale) {
  return studioContent[locale];
}
